language: java

# build time with caching:
#   11.4 download cache, 53 unzip cache, 2 configure, 10 wait for wls start = 76 (assuming no cache upload)
# build time without caching:
#   10 download zip from s3, 6 unzip, 79 configure, 52 wait for wls start = 147

env: WLS_UNZIP=$PWD/wls
     MW_HOME=$WLS_UNZIP/wls12130
     WLS_BIN=$MW_HOME/wlserver/server/bin
     DOMAIN_HOME=$WLS_UNZIP/domain_home

# test
before_script:
  - mkdir -p $WLS_UNZIP
  # download weblogic if not yet available from cache
  - test -f $WLS_UNZIP/wls.zip || wget -O $WLS_UNZIP/wls.zip https://s3-us-west-2.amazonaws.com/redheap-wls/wls1213_dev_update2.zip
  # unzip wls.zip if not yet available from cache
  - test -d $MW_HOME || unzip $WLS_UNZIP/wls.zip -d $WLS_UNZIP
  - ls -al $WLS_UNZIP
  # configure weblogic, will finish fast if already configured in cache
  - (cd $MW_HOME && . ./configure.sh -silent)
  - cat $MW_HOME/silent_install.log
  # setup WLS environment and create and start WLS domain
  - mkdir -p $DOMAIN_HOME
  - (. $WLS_BIN/setWLSEnv.sh && cd $DOMAIN_HOME && echo 'y' | 
     $JAVA_HOME/bin/java $JAVA_OPTIONS -Xmx1024m -XX:MaxPermSize=256m 
                         -Dweblogic.Domain=mydomain -Dweblogic.Name=myserver
                         -Dweblogic.management.username=weblogic -Dweblogic.management.password=weblogic1 
                         weblogic.Server &)
  # wait for WLS to complete its start in the background
  # todo: this also triggers deployment of console app which takes time
  - while true; do sleep 1; wget -q -O - http://localhost:7001/console && echo 'WLS started' && break; done

after_script:
  # todo: replace with killing weblogic as first ever wlst invoke scans classpath for 30 seconds
  - $DOMAIN_HOME/bin/stopWebLogic.sh

cache:
  directories:
    #- $WLS_UNZIP
    - $MW_HOME
    - $DOMAIN_HOME

before_cache:
  # stop weblogic before persisting cache
  - $DOMAIN_HOME/bin/stopWebLogic.sh
  # clear files that would trigger cache update when not needed
  - rm -f $MW_HOME/silent_install*.log
  - rm -f $MW_HOME/logs/*
  - rm -f $DOMAIN_HOME/config/config.lok
  # remove ldap files that seem to change at each wls run
  - rm -f $DOMAIN_HOME/servers/myserver/data/ldap/ldapfiles/*.tran
  - rm -f $DOMAIN_HOME/servers/myserver/data/ldap/ldapfiles/*.trpos
  - rm -f $DOMAIN_HOME/servers/myserver/data/ldap/ldapfiles/*.twpos
  # not sure what store is for (contains default and diagnostics subdirs that change)
  - rm -f $DOMAIN_HOME/servers/myserver/data/store/default/*
  - rm -f $DOMAIN_HOME/servers/myserver/data/store/diagnostics/*
  - rm -f $DOMAIN_HOME/servers/myserver/logs/*
  - rm -rf $DOMAIN_HOME/servers/myserver/tmp/*
