language: java

env: WLS_UNZIP=$PWD/wls MW_HOME=$WLS_UNZIP/wls12130
# test
before_script:
  - ls -al $WLS_UNZIP
  - mkdir -p $WLS_UNZIP
  - ls -al $WLS_UNZIP
  - test -f $WLS_UNZIP/wls.zip || wget -O $WLS_UNZIP/wls.zip https://s3-us-west-2.amazonaws.com/redheap-wls/wls1213_dev_update2.zip
  - ls -al $WLS_UNZIP
  - test -d $MW_HOME || unzip $WLS_UNZIP/wls.zip -d $WLS_UNZIP
  - ls -al $WLS_UNZIP
  - $MW_HOME/configure.sh -silent

cache:
  directories:
    - $WLS_UNZIP